# railway.toml

[[services]]
  name = "web"
  dev = false
  port = 3000

  build = "npm install"
  start = "npm start"

  [services.env]
    NODE_ENV = "production"

  [[services.ports]]
    external = 8080
    internal = 8080
