[[services]]
  # Service name
  name = "web"

  # Build and start command
  dev = false
  port = 3000

  # Environment variables
  [services.env]
    NODE_ENV = "production"

  # Health check endpoint
  [[services.ports]]
    external = 8080
    internal = 8080