  name = "web"

  # Build command (change accordingly)
  build = "npm install && npm run build"

  # Start command (change accordingly)
  start = "npm start"

  # Port that your app listens on
  port = 3000